#! /usr/bin/env python
import string
from random import randint
def main(): 
    # get all the keys
    letters = [ i for i in string.ascii_lowercase ]
    # print them out in random order
    while True:
        let = letters[randint(0, len(letters) - 1)] 
        print(let)
        # get the user input
        x = ""
        while x != let:
            x = input("Enter the letter you see: ")
            if x == let: break 
            print(let + "\nWrong letter!, try again: ")
# validate the input 
if __name__ == "__main__":
    try:
        main()
    except EOFError:
        pass
    except KeyboardInterrupt:
        pass
